[2022-05-23 16:17:17,750] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: httpChartDag.parseHttp manual__2022-05-23T13:17:15.853056+00:00 [queued]>
[2022-05-23 16:17:17,756] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: httpChartDag.parseHttp manual__2022-05-23T13:17:15.853056+00:00 [queued]>
[2022-05-23 16:17:17,756] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-23 16:17:17,756] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-05-23 16:17:17,756] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-23 16:17:17,766] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): parseHttp> on 2022-05-23 13:17:15.853056+00:00
[2022-05-23 16:17:17,768] {standard_task_runner.py:52} INFO - Started process 36664 to run task
[2022-05-23 16:17:17,774] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'httpChartDag', 'parseHttp', 'manual__2022-05-23T13:17:15.853056+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/httpChartDag.py', '--cfg-path', '/var/folders/0d/sktr6mh10ll3pgqmdz0_b6pw0000gn/T/tmpjlx9t1o_', '--error-file', '/var/folders/0d/sktr6mh10ll3pgqmdz0_b6pw0000gn/T/tmpwj5csck6']
[2022-05-23 16:17:17,776] {standard_task_runner.py:80} INFO - Job 53: Subtask parseHttp
[2022-05-23 16:17:17,816] {task_command.py:369} INFO - Running <TaskInstance: httpChartDag.parseHttp manual__2022-05-23T13:17:15.853056+00:00 [running]> on host 192.168.1.89
[2022-05-23 16:17:17,860] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=httpChartDag
AIRFLOW_CTX_TASK_ID=parseHttp
AIRFLOW_CTX_EXECUTION_DATE=2022-05-23T13:17:15.853056+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-23T13:17:15.853056+00:00
[2022-05-23 16:17:17,862] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/mohammadrezakhorasanchian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/Users/mohammadrezakhorasanchian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/mohammadrezakhorasanchian/airflow/dags/httpChartDag.py", line 30, in _parseHttp
    w = open("aiflow/dags/result.txt", "w")
FileNotFoundError: [Errno 2] No such file or directory: 'aiflow/dags/result.txt'
[2022-05-23 16:17:17,866] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=httpChartDag, task_id=parseHttp, execution_date=20220523T131715, start_date=20220523T131717, end_date=20220523T131717
[2022-05-23 16:17:17,874] {standard_task_runner.py:92} ERROR - Failed to execute job 53 for task parseHttp ([Errno 2] No such file or directory: 'aiflow/dags/result.txt'; 36664)
[2022-05-23 16:17:17,915] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-23 16:17:17,933] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
