[2022-05-23 17:22:18,681] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: httpChartDag.parseHttp manual__2022-05-23T14:22:16.792570+00:00 [queued]>
[2022-05-23 17:22:18,686] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: httpChartDag.parseHttp manual__2022-05-23T14:22:16.792570+00:00 [queued]>
[2022-05-23 17:22:18,686] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-23 17:22:18,686] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-05-23 17:22:18,686] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-23 17:22:18,695] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): parseHttp> on 2022-05-23 14:22:16.792570+00:00
[2022-05-23 17:22:18,697] {standard_task_runner.py:52} INFO - Started process 39283 to run task
[2022-05-23 17:22:18,702] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'httpChartDag', 'parseHttp', 'manual__2022-05-23T14:22:16.792570+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/httpChartDag.py', '--cfg-path', '/var/folders/0d/sktr6mh10ll3pgqmdz0_b6pw0000gn/T/tmpv_ytemog', '--error-file', '/var/folders/0d/sktr6mh10ll3pgqmdz0_b6pw0000gn/T/tmps3l1ak7r']
[2022-05-23 17:22:18,704] {standard_task_runner.py:80} INFO - Job 56: Subtask parseHttp
[2022-05-23 17:22:18,741] {task_command.py:369} INFO - Running <TaskInstance: httpChartDag.parseHttp manual__2022-05-23T14:22:16.792570+00:00 [running]> on host 192.168.1.89
[2022-05-23 17:22:18,782] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=httpChartDag
AIRFLOW_CTX_TASK_ID=parseHttp
AIRFLOW_CTX_EXECUTION_DATE=2022-05-23T14:22:16.792570+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-23T14:22:16.792570+00:00
[2022-05-23 17:22:22,527] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/mohammadrezakhorasanchian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/Users/mohammadrezakhorasanchian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/mohammadrezakhorasanchian/airflow/dags/httpChartDag.py", line 134, in _parseHttp
    db.collection(u'GetRequests').document(hash(x)).set(data)
  File "/Users/mohammadrezakhorasanchian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/google/cloud/firestore_v1/base_collection.py", line 131, in document
    return self._client.document(*child_path)
  File "/Users/mohammadrezakhorasanchian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/google/cloud/firestore_v1/client.py", line 209, in document
    *self._document_path_helper(*document_path), client=self
  File "/Users/mohammadrezakhorasanchian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/google/cloud/firestore_v1/base_client.py", line 320, in _document_path_helper
    joined_path = _helpers.DOCUMENT_PATH_DELIMITER.join(path)
TypeError: sequence item 1: expected str instance, int found
[2022-05-23 17:22:22,532] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=httpChartDag, task_id=parseHttp, execution_date=20220523T142216, start_date=20220523T142218, end_date=20220523T142222
[2022-05-23 17:22:22,537] {standard_task_runner.py:92} ERROR - Failed to execute job 56 for task parseHttp (sequence item 1: expected str instance, int found; 39283)
[2022-05-23 17:22:22,581] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-23 17:22:22,599] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
