[2022-05-23 16:13:29,005] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: httpChartDag.parseHttp manual__2022-05-23T13:13:26.929547+00:00 [queued]>
[2022-05-23 16:13:29,010] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: httpChartDag.parseHttp manual__2022-05-23T13:13:26.929547+00:00 [queued]>
[2022-05-23 16:13:29,010] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-23 16:13:29,010] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-05-23 16:13:29,010] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-23 16:13:29,019] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): parseHttp> on 2022-05-23 13:13:26.929547+00:00
[2022-05-23 16:13:29,021] {standard_task_runner.py:52} INFO - Started process 36323 to run task
[2022-05-23 16:13:29,025] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'httpChartDag', 'parseHttp', 'manual__2022-05-23T13:13:26.929547+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/httpChartDag.py', '--cfg-path', '/var/folders/0d/sktr6mh10ll3pgqmdz0_b6pw0000gn/T/tmp0mr5lsq1', '--error-file', '/var/folders/0d/sktr6mh10ll3pgqmdz0_b6pw0000gn/T/tmp5sx7_nge']
[2022-05-23 16:13:29,027] {standard_task_runner.py:80} INFO - Job 52: Subtask parseHttp
[2022-05-23 16:13:29,062] {task_command.py:369} INFO - Running <TaskInstance: httpChartDag.parseHttp manual__2022-05-23T13:13:26.929547+00:00 [running]> on host 192.168.1.89
[2022-05-23 16:13:29,100] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=httpChartDag
AIRFLOW_CTX_TASK_ID=parseHttp
AIRFLOW_CTX_EXECUTION_DATE=2022-05-23T13:13:26.929547+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-23T13:13:26.929547+00:00
[2022-05-23 16:13:29,102] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/mohammadrezakhorasanchian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/Users/mohammadrezakhorasanchian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/mohammadrezakhorasanchian/airflow/dags/httpChartDag.py", line 29, in _parseHttp
    f = open("http.log", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'http.log'
[2022-05-23 16:13:29,105] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=httpChartDag, task_id=parseHttp, execution_date=20220523T131326, start_date=20220523T131329, end_date=20220523T131329
[2022-05-23 16:13:29,112] {standard_task_runner.py:92} ERROR - Failed to execute job 52 for task parseHttp ([Errno 2] No such file or directory: 'http.log'; 36323)
[2022-05-23 16:13:29,124] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-23 16:13:29,140] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
